"""Subprocess adapter for the published tpchgen-cli 3.x binary."""

from __future__ import annotations

import math
import os
import re
import shutil
import subprocess
from pathlib import Path
from threading import Thread
from typing import Callable

from ..errors import GenerationError
from ..models import Generated, Options
from ..security import Redactor
from ..util import heartbeat
from .binary import get_binary


def native_environment(threads: int) -> dict[str, str]:
    env = {
        key: value
        for key, value in os.environ.items()
        if not re.search(r"TOKEN|SECRET|PASSWORD|CREDENTIAL|ACCESS_KEY|AUTHORIZATION", key, re.I)
    }
    env["RAYON_NUM_THREADS"] = str(threads)
    env["NO_COLOR"] = "1"
    return env


def parse_version(text: str) -> str:
    match = re.search(r"\btpchgen(?:-cli)?\s+(\d+\.\d+\.\d+(?:[-+][\w.-]+)?)", text, re.I)
    if not match:
        raise GenerationError(
            "Cannot identify the tpchgen-cli executable/version; supply the published 3.x binary"
        )
    version = match.group(1)
    if not version.startswith("3."):
        raise GenerationError(
            f"Unsupported tpchgen-cli {version}; this adapter requires 3.x (Parquet subcommand)"
        )
    return version


def build_command(executable: Path, options: Options, output: Path, help_text: str) -> list[str]:
    command = [str(executable), "parquet", "--scale-factor", str(options.sf), "--output-dir", str(output)]
    # Documented 3.x flags. Each partition is generated by the native binary, never combined in Python.
    parts = max(1, math.ceil(float(options.sf) / 10))
    command += ["--parts", str(parts), "--row-group-bytes", str(16 * 1024 * 1024)]
    if re.search(r"--num-threads\b", help_text):
        command += ["--num-threads", str(options.threads)]
    elif re.search(r"--threads\b", help_text):
        command += ["--threads", str(options.threads)]
    if "--no-progress" in help_text:
        command.append("--no-progress")
    return command


class TPCHGenerator:
    def __init__(self, options: Options, emit: Callable[[str], None], redactor: Redactor):
        self.options, self.emit, self.redactor = options, emit, redactor
        self.executable: Path | None = None
        self.version = ""
        self.help_text = ""
        self.details: dict = {}

    def prepare(self, scratch: Path) -> Generated:
        path = self.options.tpchgen or shutil.which("tpchgen-cli")
        if path:
            self.executable = Path(path).expanduser().resolve()
            if not self.executable.is_file() or not os.access(self.executable, os.X_OK):
                raise GenerationError("--tpchgen must point to an executable native tpchgen-cli binary")
            self.details = {"source": "user-supplied/PATH executable", "executable": str(self.executable)}
        else:
            self.executable, self.details = get_binary(
                self.options.no_download, self.options.timeout, self.emit
            )
        try:
            result = subprocess.run(
                [str(self.executable), "--version"],
                capture_output=True,
                text=True,
                timeout=self.options.timeout,
                check=True,
                env=native_environment(self.options.threads),
            )
            self.version = parse_version(result.stdout + result.stderr)
            help_result = subprocess.run(
                [str(self.executable), "parquet", "--help"],
                capture_output=True,
                text=True,
                check=True,
                timeout=self.options.timeout,
                env=native_environment(self.options.threads),
            )
            self.help_text = help_result.stdout + help_result.stderr
        except (OSError, subprocess.SubprocessError) as exc:
            raise GenerationError(f"Cannot execute tpchgen-cli on this platform: {exc}") from exc
        return Generated("tpchgen-cli", self.version, self.details)

    def generate(self, output: Path, scratch: Path) -> Generated:
        assert self.executable is not None
        output.mkdir(parents=True, exist_ok=True)
        command = build_command(self.executable, self.options, output, self.help_text)
        self.emit(f"Generate TPC-H SF={self.options.sf} using tpchgen-cli {self.version}")
        tail = bytearray()
        process = None
        reader = None
        try:
            process = subprocess.Popen(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                env=native_environment(self.options.threads),
            )
            assert process.stdout is not None

            def consume() -> None:
                assert process is not None and process.stdout is not None
                while chunk := process.stdout.read(4096):
                    tail.extend(chunk)
                    if len(tail) > 65536:
                        del tail[:-65536]

            reader = Thread(target=consume, daemon=True)
            reader.start()
            with heartbeat(self.emit, "TPC-H generation"):
                code = process.wait()
            reader.join()
            if code:
                message = self.redactor.text(bytes(tail).decode("utf-8", errors="replace"))
                raise GenerationError(f"tpchgen-cli exited with status {code}: {message[-12000:]}")
        except (KeyboardInterrupt, SystemExit):
            if process and process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait()
            raise
        except OSError as exc:
            raise GenerationError(f"Could not run tpchgen-cli: {exc}") from exc
        finally:
            if reader:
                reader.join(timeout=5)
            if process and process.stdout:
                process.stdout.close()
        return Generated("tpchgen-cli", self.version, {**self.details, "arguments": command[1:]})

    def close(self) -> None:
        pass
